<a href="https://colab.research.google.com/github/matsunori39/Small-Data-Analysis-and-Machine-Learning/blob/main/Small_Data_Analysis_and_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.ohmsha.co.jp/book/9784274227783/

# Chapter 2 Correlation and Principal Component Analysis

## 2.1 Data Preprocessing

### Data Standardization

In [69]:
import numpy as np

def autoscale(X):
  """
  Standardize data matrix

  Parameters
  ------------
  X: Data Matrix

  Return Value
  ------------
  Xscale: Data matrix after standardization
  meanX: mean vector
  stdX: standard deviation vector
  """

  meanX = np.mean(X, axis = 0)
  stdX = np.std(X, axis = 0, ddof = 1)
  Xscale = (X - meanX) / stdX
  return Xscale, meanX, stdX

def scaling(x, meanX, stdX):
  """
  Standardizes the sample from mean and standard deviation of the data matrix

  Parameters
  ------------
  x: Samples to be standardized
  meanX: mean vector
  stdX: standard deviation vector

  Return Value
  ------------
  xscale: Sample after standardization
  """

  xscale = (x - meanX) / stdX
  return xscale

def rescaling(xscale, meanX, stdX):
  """
  Restore standardized samples to original scale

  Parameters
  ------------
  xscale: Sample after standardization
  meanX: mean vector
  stdX: standard deviation vector

  Return Value
  ------------
  xscale: Sample of original scale
  """

  x = np.multiply(stdX, xscale) + meanX
  return x

### Standardize data

In [70]:
import numpy as np

# Define existing data and unknown samples with ndarray type
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

x = np.array([[10, 11, 12]])

# Standardize X
Xscale, meanX, stdX = autoscale(X)
print(Xscale)

[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]


In [71]:
print(meanX)

[4. 5. 6.]


In [72]:
print(stdX)

[3. 3. 3.]


In [73]:
# Stdndardize unknown samples
xscale = scaling(x, meanX, stdX)
print(xscale)

[[2. 2. 2.]]


In [74]:
# Restore the standardized sample to its original scale
xrescale = rescaling(xscale, meanX, stdX)
print(xrescale)

[[10. 11. 12.]]


## 2.8 Derivation of the rth principal component

### PCA program with eigenvalue problem

In [75]:
import numpy as np

def pca(X):
  """
  Performs principal component analysis with eigenvalues

  Parameter
  ------------
  X: Data Matrix

  Return Values
  ------------
  P: Loading Matrix
  t: Principal Component Score Matrix  
  """

  # Computes the covariance matrix
  V = np.cov(X.T)
  # Solve the eigenvalue problem for the covariance matrix
  _, P = np.linalg.eig(V)

  # Calculate principal component scores
  t = X @ P
  return P, t

## 2.9 Examples of PCA values

In [76]:
import numpy as np

data = [[2, 2], [1, -1], [-1, 1], [-2, -2]]
x = np.array(data)
P, T = pca(x)

print(P)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## 2.12 PCA and Singular Value Decomposition

### PCA using SVD

In [77]:
import numpy as np

def pca_svd(X):
  """
  Perform principal component analysis using SVD

  Parameter
  ---------
  X: Data Matrix

  Return Values
  ---------
  P: Loading Matrix
  t: Principal Component Score Matrix
  """

  # Decompose a matrix into singular values
  _, _, P = np.linalg.svd(X)

  # Calculate principal component scores
  t = X @ P.T
  return P, t

In [78]:
P, t = pca_svd(np.array(data))
print(P)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


# Chapter 3 Regression Analysis and Least Squares Method

## 3.2 Least Squares Method

In [79]:
import numpy as np

def least_squares(X, y):
  """
  Calculate regression coefficients using the least squares method

  Parameters
  ----------
  X: input data
  y: output data

  Return Value
  ----------
  beta: regression coefficient
  """

  # Vectorize y
  y = y.reshape(-1, 1)

  # normal equation
  beta = np.linalg.inv(X.T @ X) @ X.T @ y
  return beta

def ls_est(x, beta):
  """
  Predicts output using a linear regression model

  Parameters
  ----------
  x: unknown sample
  beta: regression coefficient

  Return Value
  ----------
  y_hat: Predicted value
  """

  y_hat = beta.T @ x
  return y_hat

### Numerical example of the least-squares method

In [80]:
import numpy as np

# Define data
X = np.array([[0.01, 0.50, -0.12],
              [0.97, -0.63, 0.02],
              [0.41, 1.15, -1.17],
              [-1.38, -1.02, 1.27]])

y = np.array([[0.25], [0.08], [1.03], [-1.37]])
x = np.array([1, 0.7, -0.2])

# Find the regression coefficient
beta = least_squares(X, y)
print(beta)

[[ 0.36347065]
 [ 0.41624871]
 [-0.34677593]]


In [81]:
# Predicts output from unknown samples
y_hat = ls_est(x, beta)
print(y_hat)

[0.72419993]


## 3.7 Multicollinearity issues

In [82]:
A = np.array([[2.01,   1 ],
              [  4 , 2.01]])
B = np.array([[1.99,   1 ],
              [  4 , 2.02]])

In [83]:
np.linalg.inv(A)

array([[ 50.12468828, -24.93765586],
       [-99.75062344,  50.12468828]])

In [84]:
np.linalg.inv(B)

array([[ 102.02020202,  -50.50505051],
       [-202.02020202,  100.50505051]])

In [85]:
C = np.array([[ 2 , 1 ],
              [ 4 , 2 ]])

In [86]:
np.linalg.cond(A)

625.4397976337879

In [87]:
np.linalg.cond(B)

1264.670926452252

In [88]:
np.linalg.cond(C)

2.517588727560788e+16

### For data without multicolinearity

In [89]:
import numpy as np

# Define data
X1 = np.array([[0.01, 0.50, -0.12],
               [0.97, -0.63, 0.02],
               [0.41, 1.15, -1.17],
               [-1.38, -1.02, 1.27]])

X2 = np.array([[-0.01, 0.52, -0.12],
               [0.96, -0.64, 0.03],
               [0.43, 1.14, -1.17],
               [-1.38, -1.01, 1.27]])

In [90]:
np.linalg.cond(X1.T @ X1)

135.7529385871794

In [91]:
np.linalg.cond(X2.T @ X2)

133.3934657598505

In [92]:
y = np.array([[0.25], [0.08], [1.03], [-1.37]])

# Calculate the regression coefficients for each of X1 and X2
beta1 = least_squares(X1, y)
print(beta1)

[[ 0.36347065]
 [ 0.41624871]
 [-0.34677593]]


In [93]:
beta2 = least_squares(X2, y)
print(beta2)

[[ 0.37270979]
 [ 0.41379869]
 [-0.34252764]]


### For multicolinear data

In [94]:
import numpy as np

# Define data (※ 0.25 * column1 - 0.8 * column2 = column3)
X1 = np.array([[-1.12, -0.51, 0.69],
               [-0.43, -1.12, 1.02],
               [0.37, 1.10, -0.98],
               [1.19, 0.53, -0.73]])

X2 = np.array([[-1.12, -0.51, 0.70],
               [-0.43, -1.12, 1.01],
               [0.36, 1.10, -0.98],
               [1.20, 0.53, -0.73]])

In [95]:
np.linalg.cond(X1.T @ X1)

235456.75658377822

In [96]:
np.linalg.cond(X2.T @ X2)

470649.9730137264

In [97]:
y = np.array([0.4, 1.17, -1.14, -0.42])

# Calculate the regression coefficients for each of X1 and X2
beta1 = least_squares(X1, y)
print(beta1)

[[0.54496962]
 [0.24094799]
 [1.64044474]]


In [98]:
beta2 = least_squares(X2, y)
print(beta2)

[[-0.42794288]
 [-2.86298696]
 [-2.2029719 ]]


## 3.10 Principal Component Regression (PCR)

In [99]:
import numpy as np

def pcr(X, y, R):
  """
  Calculate regression coefficients using PCR

  Parameters
  ----------
  X: Input Data
  y: Output Data
  R: Number of Principal Components

  Return Values
  ----------
  beta: Regression Coefficient
  """

  # Vectorize y
  y = y.reshape(-1, 1)

  # (Number of conditions before PCA)
  print(f"Number of conditions before PCA", np.linalg.cond(X.T @ X))

  # Principal Component Analysis
  P, T = pca(X)

  # Extract the principal component score matrices up to the Rth
  T = T[:,:R]

  # (Number of conditions after PCA)
  print(f"Number of conditions after PCA", np.linalg.cond(T.T @ T))

  # Find the regression coefficient by the least squares method
  beta_R = least_squares(T, y)
  beta = P[:,:R] @ beta_R
  return beta

### If the number of principal components is 2

In [100]:
import numpy as np

# Define data (※ 0.25 * column1 - 0.8 * column2 = column3)
X1 = np.array([[-1.12, -0.51, 0.69],
               [-0.43, -1.12, 1.02],
               [0.37, 1.10, -0.98],
               [1.19, 0.53, -0.73]])

X2 = np.array([[-1.12, -0.51, 0.70],
               [-0.43, -1.12, 1.01],
               [0.36, 1.10, -0.98],
               [1.20, 0.53, -0.73]])

In [101]:
y = np.array([0.4, 1.17, -1.14, -0.42]) 

In [102]:
# Set the number of principal components to 2
R = 2

beta1 = pcr(X1, y, R)

Number of conditions before PCA 235456.75658377822
Number of conditions after PCA 8.080825169090927


In [103]:
print(beta1)

[[ 0.25849154]
 [-0.68874152]
 [ 0.49387146]]


In [104]:
beta2 = pcr(X2, y, R)

Number of conditions before PCA 470649.9730137264
Number of conditions after PCA 7.975485263932513


In [105]:
print(beta2)

[[ 0.25929082]
 [-0.69212429]
 [ 0.49149105]]


### If the number of principal components is 1

In [106]:
# Set the number of principal components to 1
R = 1

beta1 = pcr(X1, y, R)

Number of conditions before PCA 235456.75658377822
Number of conditions after PCA 1.0


In [107]:
print(beta1)

[[-0.30313539]
 [-0.32858522]
 [ 0.34217102]]


In [108]:
beta2 = pcr(X2, y, R)

Number of conditions before PCA 470649.9730137264
Number of conditions after PCA 1.0


In [109]:
print(beta2)

[[-0.30335458]
 [-0.32755389]
 [ 0.34127419]]


## 3.11 Ridge regression

In [111]:
import numpy as np

def ridge(X, y, mu=0.1):
  """
  Calculate regression coefficients using ridge regression

  Parameters
  ----------
  X: Input Data
  y: Output Data
  mu: Parameter (default: 0.1)

  Return Values
  ----------
  beta_ridge: Regression Coefficient
  """
  # Vectorize y
  y = y.reshape(-1, 1)

  # Find the regression coeeficients for the Ridge regression
  I = np.eye(X.shape[1])
  # (Number of conditions before Ridge)
  print(f"Number of conditions before Ridge", np.linalg.cond(X.T @ X))
  # (Number of conditions after Ridge)
  print(f"Number of conditions after Ridge", np.linalg.cond(X.T @ X + mu * I))
  beta_ridge = np.linalg.inv(X.T @ X + mu * I) @ X.T @ y
  return beta_ridge

### Examples of Ridge regression

In [112]:
# Set the parameter to 0.1
mu = 0.1
beta1 = ridge(X1, y, mu)

Number of conditions before Ridge 235456.75658377822
Number of conditions after Ridge 81.12782634914616


In [113]:
print(beta1)

[[ 0.21088992]
 [-0.65139114]
 [ 0.47615414]]


In [114]:
beta2 = ridge(X2, y, mu)

Number of conditions before Ridge 470649.9730137264
Number of conditions after Ridge 81.11600505494289


In [115]:
print(beta2)

[[ 0.21198147]
 [-0.65545325]
 [ 0.47322964]]


In [116]:
# Set the parameter to 1
mu = 1
beta1 = ridge(X1, y, mu)

Number of conditions before Ridge 235456.75658377822
Number of conditions after Ridge 9.015237530107033


In [117]:
print(beta1)

[[ 0.01017256]
 [-0.47145393]
 [ 0.3798    ]]


In [118]:
beta2 = ridge(X2, y, mu)

Number of conditions before Ridge 470649.9730137264
Number of conditions after Ridge 9.012828087473903


In [119]:
print(beta2)

[[ 0.01227368]
 [-0.47396013]
 [ 0.37864896]]
